#!/bin/bash
declare -a argv
for ((i=1;i<=${#@};i+=1))
do

   arg=${@:i:1}

   if [[ "$arg" == "--preload"* ]];then
      i=$i+1
      marg=${@:$((i)):1}
      preLoadO=$arg
      preLoadA=" \"${marg}\""
      argv=("${argv[@]}" $arg)
      argv=("${argv[@]}" $preLoadA)

   elif [[ "$arg" == "--postload"* ]];then
      i=$i+1
      marg=${@:$((i)):1}
      postLoadO=$arg
      postLoadA=" \"${marg}\""
      argv=("${argv[@]}" $arg)
      argv=("${argv[@]}" $postLoadA)       
   else          
      argv=("${argv[@]}" $arg)
   fi
done

arguments=$(printf " %s" "${argv[@]}")
arguments=${arguments:1}

listener() {
    while IFS= read -r line; do
        echo "$(date) $line"
    done
}

#FULLSCRIPTPATH="$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"
#SCRIPTDIR=$(dirname ${FULLSCRIPTPATH})
SCRIPTDIR='/usr/karotz/rofra/karotzVmAnalyser'

mkdir -p /tmp/karotzvmlog/

# Get the variables needed
UUID=$(uuidgen)
FILENOIN="${UUID}.in.log"
FILENOOUT="${UUID}.out.log"
FILENOLAU="${UUID}.launch.log"
FILENOTRAP="${UUID}.trap.log"

# Log the launch
echo "`date -u` Executing original Karotzvm [${UUID}] with params [${arguments}]" >> /tmp/karotzvmlog/launch.log


# Log the launch with args
echo "${SCRIPTDIR}/karotzVMOriginal $arguments" > /tmp/karotzvmlog/${FILENOLAU}


# Log the ouput
#exec 1>> "/tmp/karotzvmlog/${FILENOOUT}" 2>&1

# Log everything else put into the stdin
tee "/tmp/karotzvmlog/${FILENOIN}"|${SCRIPTDIR}/karotzVMOriginal $arguments &

# OR without tee
#${SCRIPTDIR}/karotzVMOriginal $arguments &
#
PIID=$!

# TRAP ALL
i=-1; while((++i<33));
do
    trap "echo \"\`date -u\` $i\" >> /tmp/karotzvmlog/${FILENOTRAP}; kill -$i ${PIID};" $i;
done

#sleep 365d
#wait
wait ${PIID}

